name: "Build and test"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Gather dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgtest-dev
    - name: Run unit tests
      run: |
        g++ -o runtests -I./include/ -lgtest_main -lgtest -lpthread tests/test_glyph.cpp src/glyph.cpp
        ./runtests
